on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
